'use client'

import { Inter } from 'next/font/google';
import { useEffect, useState } from "react";
import Aside from "./componnent/Aside";
import Header from "./componnent/Header";
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export default function RootLayout({ children }) {

  const [isshow, setisshow] = useState(false);

  useEffect(() => {
    window.addEventListener("resize", () => {
      if (window.innerWidth > 640) {
        setisshow(false);
      }
    })
  });


  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='grid layoutWrp'>
          <Aside isshow={isshow} />
          <div className="rounded-lg w-full h-screen contentWrp">
            <Header isshow={isshow} setisshow={setisshow} />
            <div className="mt-6 mr-4 ml-4">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
